-- CREATE TABLE `collections` (
--     `id` BIGINT NOT NULL AUTO_INCREMENT,
--     `collectionId` BIGINT NOT NULL,
--     `itemId` BIGINT NOT NULL,
--     PRIMARY KEY (`id`),
--     INDEX `collectionId` (`collectionId`)
-- ) ENGINE = InnoDB
-- DEFAULT CHARSET=utf8mb4
-- COLLATE=utf8mb4_general_ci;